### ISSUE TITLE
Update README to indicate that --packages can be passed to spark-shell

### ISSUE THREAD

**Issue by mlaccetti** [unchartedsoftware/sparklet#5]
The command needs to fire up `spark-shell` with some `--packages`

**Comment by Ghnuberath** [comment]
Such as? Wouldn't this be too opinionated, since we don't know what folks are going to be using spark  for?

**Comment by mlaccetti** [comment]
How about: add the ability to add them on the docker run command?

**Comment by Ghnuberath** [comment]
That makes more sense to me, but it's already possible:

```bash
$ docker run -it uncharted/sparklet:1.6.1 spark-shell --packages software.uncharted.sparkpipe:sparkpipe-core:0.9.7
```

**Comment by mlaccetti** [comment]
Fiiiiiiine – update the README, then?!
